//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTechnoloshe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechnolosheProyectoEntities1 : DbContext
    {
        public TechnolosheProyectoEntities1()
            : base("name=TechnolosheProyectoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalogo> Catalogos { get; set; }
        public virtual DbSet<Estrella> Estrellas { get; set; }
        public virtual DbSet<Nebulosa> Nebulosas { get; set; }
        public virtual DbSet<Planeta> Planetas { get; set; }
    }
}
