//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTechnoloshe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nebulosa
    {
        public int ID { get; set; }
        public int IDCatalogo { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public int DistanciaParsecs { get; set; }
        public decimal MagnitudAbsoluta { get; set; }
        public bool VisibilidadHS { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
    }
}
